spring:
  profiles: dev
appConfiguration:
  backEndUrl: http://localhost:8080
  enableSwagger: true
databaseConfiguration:
  url: jdbc:h2:file:/data/demo
  username: sa
  password: password
  driver: org.hibernate.dialect.H2Dialect